### ISSUE TITLE
some question about SOT

### ISSUE THREAD

**Issue by zlxhhh** [open-mmlab/mmtracking#106]
hello，when i use sot, i meet some questions:
1.When using SOT, the target I want to track is framed, but bbox cannot track it well, I want to know if it is the problem with my method or the model itself has limitations
2.demo_SOT cannot save each frame to the folder specified by output like demo_MOT
3.If the bbox of an object in the middle of the video is known, can SOT be used to obtain the bbox information of the entire video target? 
thanks a lot
![LI($037$)F89 )$(}~%%PPC](https://user-images.githubusercontent.com/34005222/107568048-70601e00-6c21-11eb-888f-ed9e11b0db88.png)
![N`K7A9$I10_`QQJ274P2_Q1](https://user-images.githubusercontent.com/34005222/107568052-7229e180-6c21-11eb-81f7-28df5f8c0b1a.png)
![NZ 5}3IAU~1FWAL$W0}_2PN](https://user-images.githubusercontent.com/34005222/107568055-735b0e80-6c21-11eb-893c-69e872f9156b.png)

**Comment by GT9505** [comment]
1. Single object tracker cann't always track a target if the target moves fast or out of boundary. Therefore, If you don't modify the code and use the pretrained model provided by us, the tracking results are still poor. Maybe the model have some limitations.
2. You can save `frame` after [this line](https://github.com/open-mmlab/mmtracking/blob/master/demo/demo_sot.py#L62) to a directory in order to get per frame results.
3. Yes. Taking the given frame in the middle of video as 'the first frame', you need run demo twice in the positive and negative directions.

**Comment by zlxhhh** [comment]
What puzzles me is that the selected target（the boy） in this video doesn't move fast and doesn't out of boundary. Can you watch this video and analyze the specific reasons?
link：https://pan.baidu.com/s/1R4D5ZfSKiz_2lKh01jTsfA 
Extraction code ：ej1x

**Comment by GT9505** [comment]
The SiameseRPN++ tracker works well. You can watch [this video](https://drive.google.com/file/d/13si2j3m0x5qQN504nWITNaEomOEfI9R-/view?usp=sharing). By the way, did you download the [trained model](https://download.openmmlab.com/mmtracking/sot/siamese_rpn/siamese_rpn_r50_1x_lasot/siamese_rpn_r50_1x_lasot_20201218_051019-3c522eff.pth)?
