### ISSUE TITLE
question about ref_img_sampler parameters (num_ref_imgs, frame_range, filter_key_img )

### ISSUE THREAD

**Issue by fcakyon** [open-mmlab/mmtracking#154]
@OceanPang @GT9505 Thanks a lot for maintaining this library!

I read the related docs on these params but couldnt understand their meaning, would you tell their meaning and what they change during training:

`num_ref_imgs`, `frame_range`, `filter_key_img` from [this config](https://github.com/open-mmlab/mmtracking/blob/56f2383c369e8f14ddbe8ff99c51853984b5e1e6/configs/_base_/datasets/imagenet_vid_fgfa_style.py#L41).

What is the difference between [this](https://github.com/open-mmlab/mmtracking/blob/56f2383c369e8f14ddbe8ff99c51853984b5e1e6/configs/_base_/datasets/imagenet_vid_fgfa_style.py#L41) and [this](https://github.com/open-mmlab/mmtracking/blob/56f2383c369e8f14ddbe8ff99c51853984b5e1e6/configs/_base_/datasets/imagenet_vid_fgfa_style.py#L52) as given:
`num_ref_imgs=9, frame_range=9, filter_key_img=True`
`num_ref_imgs=2, frame_range=0, filter_key_img=True`

**Comment by OceanPang** [comment]
Hi @fcakyon, `num_ref_imgs` means the number of reference images you want to sample.
`frame_range` means the frame intervals to sample the images and `filter_key_img` means whether you will put the keyframe itself when sampling reference images.
For example, a key image locates at frame t. If `frame_range == 2`, the sampling candidates will be the images in `t-2 -> t+2`.

**Comment by OceanPang** [comment]
@fcakyon Sorry for the late reply. 
This seems an implementation bug. @GT9505, can you take a look at this config?

**Comment by GT9505** [comment]
The code for sampling reference images is in [here](https://github.com/open-mmlab/mmtracking/blob/master/mmtrack/datasets/coco_video_dataset.py#L94).
This is a bug, which may introduce some misunderstanding, in the vid config. The `filter_key_img` should be `False`, when the training data is images rather than videos. But it don't change the output of the function, since the function directly copy the input image with `num_ref_imgs` times, as long as `frame_range=0`.
We will fix it in next PR.

**Comment by fcakyon** [comment]
@GT9505 thanks for the feedback.
