### ISSUE TITLE
Question about demo_vid.py and inference.py for SELSA

### ISSUE THREAD

**Issue by Cospel** [open-mmlab/mmtracking#174]
Hi, I'm trying to inspect how the SELSA model is working and how to make prediction on sequence of video frames. I already trained my model and now want to test it. I want to use 2 previous frames and 2 future frames to make prediction for time t.

Should I modify ref_img_sampler in inference_vid method? What is sampling stride param doing?

**Comment by GT9505** [comment]
You can pass `ref_img_sampler` to this [function](https://github.com/open-mmlab/mmtracking/blob/master/demo/demo_vid.py#L46), and the docstring of the function is in [here](https://github.com/open-mmlab/mmtracking/blob/master/mmtrack/apis/inference.py#L136).
Currently, we only support online mode when running `demo_vid.py`, i.e. only previous frames can be used as reference frames. You also don't need worry about the performace, since the performance of only using previous frames is slightly worse (around 0.2 mAP on ImageNet VID dataset) than using both pervious and future frames, if the number of support frames keep the same.

**Comment by GT9505** [comment]
The sampling stride means we sample a frame as reference frame every `frame_stride` frames.
