### ISSUE TITLE
Missing required parameter ```show-score-thr```

### ISSUE THREAD

**Issue by dzambrano** [open-mmlab/mmtracking#265]
**Describe the bug**
Missing default value for argument ```show-score-thr``` in ```mot_param_search.py```

**Reproduction**

The command line error:
```
Traceback (most recent call last):
  File "tools/mot_param_search.py", line 220, in <module>
    main()
  File "tools/mot_param_search.py", line 190, in main
    args.show_dir, args.show_score_thr)
AttributeError: 'Namespace' object has no attribute 'show_score_thr'
```
This because the ```single_gpu_test``` methods has a required parameter ```show_score_thr```. In ```test.py``` this parameter is set by default as:
```
       parser.add_argument(
        '--show-score-thr',
        type=float,
        default=0.3,
        help='score threshold (default: 0.3)')
```

**Bug fix**
A pretty easy solution is to add:
```
       parser.add_argument(
        '--show-score-thr',
        type=float,
        default=0.3,
        help='score threshold (default: 0.3)')
```
in ```mot_param_search.py```. 

Any reason why this has not been done?

**Comment by GT9505** [comment]
It is unnecessary to pass `show-score-thr` to `single_gpu_test` function in mot, since all bbox results are needed to visualize.
For the source code of mot visualization, please refer to [here](https://github.com/open-mmlab/mmtracking/blob/master/mmtrack/models/mot/base.py#L222).
You can delete the `args.show_score_thr` in [Line 190](https://github.com/open-mmlab/mmtracking/blob/master/tools/mot_param_search.py#L190) to fix the bug.

By the way, it would be very appreciated if you could create a PR to fix the bug.

**Comment by dzambrano** [comment]
I am glad to create a PR. I guess I would need to be added as contributor first.
