### ISSUE TITLE
Calculate mAP of a given video dataset

### ISSUE THREAD

**Issue by roowang** [open-mmlab/mmtracking#277]
Sorry for bothering again.
I have followed the steps below:
python demo/demo_vid.py \
    ${CONFIG_FILE}\
    --input ${INPUT} \
    --checkpoint ${CHECKPOINT_FILE} \
    [--output ${OUTPUT}] \
    [--device ${DEVICE}] \
    [--show]
and got an output mp4 inference video. Now I want to calculate the mAP of the output video and wish to use tools/train.py but notice that it only support standard dataset. Could you give me some advice?

**Comment by GT9505** [comment]
1. You can convert the groudtruth of the video to COCOVID format following [here](https://github.com/open-mmlab/mmtracking/blob/master/docs/tutorials/customize_dataset.md#convert-the-dataset-into-cocovid-style). A simple example of COCOVID format is presented at [here](https://github.com/open-mmlab/mmtracking/blob/master/tests/data/demo_cocovid_data/ann.json).
2. Using [`CocoVideoDataset`](https://github.com/open-mmlab/mmtracking/blob/master/mmtrack/datasets/coco_video_dataset.py#L14) class to load the annotations and images.
3. Using `tools/test.py`  to test and evaluate the results, or using `tools/train.py` to train your model on your dataset.

**Comment by roowang** [comment]
How to construct images from a custom video? Do I need to divide the video into several frames or sample the video? I am confused. Thanks!

**Comment by roowang** [comment]
And is it possible to get the COCOVID format automately  by writing codes? I have read several codes but still do not know how to write. I just have a video with bbox which needs to calculate mAP.

**Comment by GT9505** [comment]
As shown in the [example of annotation file](https://github.com/open-mmlab/mmtracking/blob/master/docs/tutorials/customize_dataset.md#convert-the-dataset-into-cocovid-style), you need to set the `id=1` for the video, firstly.
Then, please count images in the video starting at `frame_id=0` and `id=1`. Note that the `video_id` in each image should be `1`, since it belongs to the video.
Finally, please count the annotations of box starting at `id=1`. You also need set `image_id` properly based on which image it belongs, and `video_id` to `1` since all annotations belong to one video.

Here is an [example of code](https://github.com/open-mmlab/mmtracking/blob/master/tools/convert_datasets/ilsvrc/imagenet2coco_vid.py) to generate such a annotation file.

**Comment by roowang** [comment]
So, do I need to generate images from the video because the example of code needs a file named Lists/VID_train_15frames.txt? How to get the file from a custom dataset?
