### ISSUE TITLE
Using mmdetection pertained model for multiple object tracking

### ISSUE THREAD

**Issue by AyeshaNirma** [open-mmlab/mmtracking#288]
I am new to tracking not to object detection or mmdetection. My question is, I have a pertained model for object detection say cascade rcnn r-50 trained on coco, of course using mmdetection. Now, I want simply to test how well it performs for car tracking (in a scene where I have multiple cars at the same time passing by). Can I use it out of the box, where each car gets a unique id (box color is unique) ? I am a bit confused regarding how to create a config file for the demo, I mean which tracking method is best suited for this problem (tractor, Siameserpn etc.). Could you please help me.

**Comment by GT9505** [comment]
The Tracktor method is more suitable for the problem since you want to track multiple objects at the same time.

However, the pretrained models provided by mmtracking can only track pedestrians, since the models are trained on MOT Challenge dataset which focuses on tracking pedestrians in crowded scenes.

The Tracktor method needs two sub-models: a detector model and a reid model. The detector model is necessary to perform tracking, while the reid model is optional to boost the performance.

Therefore, you need to train a detector that can detect cars and a reid model (optional) which can re-identify cars.
