### ISSUE TITLE
Many errors when training ReID of Tractor model on MOT17.

### ISSUE THREAD

**Issue by sjtuytc** [open-mmlab/mmtracking#339]
I ran successfully the official tractor repo, but I cannot run this repo.
Same command (default training command of Reid model), but different errors on different days.

![image](https://user-images.githubusercontent.com/31123348/143373007-1dc63b28-95b0-4ab8-bf0b-c601b104646d.png)
![image](https://user-images.githubusercontent.com/31123348/143373013-f4049fb3-f8bb-4805-94ea-4b4b5b61a9b8.png)
![image](https://user-images.githubusercontent.com/31123348/143373028-957577f9-e246-4907-841d-df2a8bc52916.png)

**Checklist**

1. I have searched related issues but cannot get the expected help.
2. The bug has not been fixed in the latest version.

**Describe the bug**

**Reproduction**

1. What command or script did you run?

```none
A placeholder for the command.
```

2. Did you make any modifications on the code or config? Did you understand what you have modified?
3. What dataset did you use and what task did you run?

**Environment**

1. Please run `python mmtrack/utils/collect_env.py` to collect necessary environment information and paste it here.
2. You may add addition that may be helpful for locating the problem, such as
    - How you installed PyTorch [e.g., pip, conda, source]
    - Other environment variables that may be related (such as `$PATH`, `$LD_LIBRARY_PATH`, `$PYTHONPATH`, etc.)

**Error traceback**
If applicable, paste the error trackback here.

```none
A placeholder for trackback.
```

**Bug fix**
If you have already identified the reason, you can provide the information here. If you are willing to create a PR to fix it, please also leave a comment here and that would be much appreciated!

**Comment by sjtuytc** [comment]
1、最好在训练前就把环境查好，不然跑着跑着报错很难受。
2、如果底层库不solid，尽量别套娃。不然依赖库报错了，查不到，太难受了。一个stand alone的仓库更受欢迎。

**Comment by GT9505** [comment]
Please fill the `reproduction` and `environment` section in the [error-report.md](https://github.com/open-mmlab/mmtracking/blob/master/.github/ISSUE_TEMPLATE/error-report.md) to provide more information of the bug.

**Comment by GT9505** [comment]
Did you train reid model on MOT20 dataset? The length of MOT17 val set can not be 180k+, while the length of MOT20 val set could be.

When evaluating in reid, a [tensor](https://github.com/open-mmlab/mmtracking/blob/master/mmtrack/datasets/reid_dataset.py#L152) with shape `(188417, 128)` will be used to calculate mAP, which may cause OOM error. Therefore,  the program always crashed in the eval hook.

Please not do evaluation hook when the length of val set of reid dataset is too long. You can set [no-validate](https://github.com/open-mmlab/mmtracking/blob/master/tools/train.py#L27) in train.py to not evaluate the checkpoint during training.

**Comment by JoJoliking** [comment]
@GT9505  Thanks for your help. I want to test on MOTChallenge test datasets. Does mmtracking provide a api for converting output data to the submission format of MOTChallenge ?

**Comment by JoJoliking** [comment]
The submission format of MOTChallenge is the .txt, and they are arranged the output by dataset name.

**Comment by JoJoliking** [comment]
The submission format of MOTChallenge is the .txt, and they are arranged the output by dataset's name.

**Comment by GT9505** [comment]
Please refer to this [API](https://github.com/open-mmlab/mmtracking/blob/master/mmtrack/datasets/mot_challenge_dataset.py#L134)

**Comment by JoJoliking** [comment]
@GT9505 I have an advice about the `crop_imgs` function in base_tracker. 
In this function, bboxes size will be limited in `min=0, max=w` and ` min=0, max=h ` by torch.clamp. 
Actually, when the bbox coordinate is equal to the length and width boundy value of the image,  this limitation have been rasing problems and bug because of the next code `x2 = x1 + 1` and `y2 = y1 + 1`.
I think that the predited bboxes are not always correct by motion preditction and the problem can be solved by coding as
`max=w - 1` and `max=h - 1`.
I have test  trackotr++ on mot15-half and mot17-half. The results are the same as the privious version.

**Comment by JoJoliking** [comment]
@GT9505 I have an advice about the crop_imgs function in base_tracker.py.
In this function, bboxes size will be limited in `min=0, max=w` and `min=0, max=h` by `torch.clamp`.
Actually, when the bbox coordinate is equal to the height boundy value (`y1 == y2`) or width boundy value (`x1 == x2`) of the image, this limitation have rasied problems and bug because of the next code `x2 = x1 + 1` and `y2 = y1 + 1`.
I think that the preditcted bboxes by motion preditction are not always correct and the problem can be solved by coding as
`max=w -1` and `max=h-1`.
I have test tracktor++ on mot15-half and mot17-half. The improved results are the same as the privious version.

**Comment by GT9505** [comment]
Hi, @JoJoliking could you create a PR to show the changes of code.

**Comment by JoJoliking** [comment]
@GT9505 It's my pleasure. I will git push my changes later.
