### ISSUE TITLE
SELSA question with MS ROI Align

### ISSUE THREAD

**Issue by Chop1** [open-mmlab/mmtracking#342]
Looking at the integration of SELSA modules with  detector using MS ROI Align, I have summarized my interpretation of how it works below.

![Untitled Diagram-Page-1-3](https://user-images.githubusercontent.com/22441193/143559332-5627f209-1fec-49ad-9ccf-0526d1fbea30.png)

If this is correct, there is somes points that are fuzzy for me.

- after performing MS ROI Align, extracted features are flattened and pass through FC layers then SELSA. It is done for multiple frames in order to use the SELSA (target + multiple support frames). Since one of the idea of SELSA is to treat video as a bag of unordered frames, I believe that the support frames also pass through MS ROI Align, using all the other frames (including target) as their own support frames ?

exemple: I have 3 frames, F1, F2, F3. F2 is the target frame

Support frame also need to pass through MS ROI Align, and thus need support frame. F1 use F2 and F3 as support frames. Since all proposal features are already extracted the additional cost is not hight.

 
- looking at SELSA paper, I do not see where it mention the attention stuff. I believe that the "old" version used the generalized cosine similarity, but you switched to attention ? Or the cosine similarity is to match related proposals between eachothers, while the attention part is omitted in the paper ?

- Are SELSA and MS ROI Align redundant methods ? Like they both try to tackle the same problem, but we observe that they can be use together to improve results ? 

Thanks a lot for this work.

**Comment by GT9505** [comment]
1. Only the proposals of target frame are passed through both ROI Align and MS ROI Align. The proposals of support frames are only passed through MS ROI Align. 
2.  We don't know whether the paper of SELSA used multi-head attention, since it didn't release codes. We adopt multi-head attention since it is a general trick to improve performance.
3. For the difference between SELSA and MS ROI Align, please refer to the introduction section of the [paper](https://arxiv.org/pdf/2109.03495.pdf). We paste the corresponding descriptions in [picture_1](https://user-images.githubusercontent.com/26813582/144582525-14b9b50d-c3e9-41f4-8825-a02dfe79862b.png) and [picture_2](https://user-images.githubusercontent.com/26813582/144582678-5a20203e-7bc2-4948-b5ea-b3b3c90c80eb.png).

**Comment by GT9505** [comment]
For the proposals of target frame, we use the feature map of target frame and the feature map of support frames to extract ROI features (i.e., ROI Align -> MS ROI Align -> TAFA).
For the proposals of support frame, we only use the feature map of support frame to extract ROI features (i.e., ROI Align).
