### ISSUE TITLE
training MOT dataset

### ISSUE THREAD

**Issue by mehmetcanmitil** [open-mmlab/mmtracking#555]
hello everyone. thank you for your answers in advance. i am new here, forgive me if i can't explain myself. I am trying to train the mot dataset. but i have a problem with pytorch. torch.distributed.launch is giving me error. i need to change to torhcrun (Transitioning from torch.distributed.launch to torchrun)but i couldn't modify the train.py script. can you please help me with that?
thanks again.

**Comment by dyhBUPT** [comment]
I'm sorry but I can't understand your problem clearly.
If it's caused by the installation of pytorch, maybe you should raise the issue in the [pytorch repo](https://github.com/pytorch/pytorch).
If you're sure it's the problem caused by the mmtracking repo, please use issue [template](https://github.com/open-mmlab/mmtracking/tree/master/.github/ISSUE_TEMPLATE) to provide more details about your issue.

**Comment by mehmetcanmitil** [comment]
I mean, I am trying to train MOT model. I used this command:
bash ./tools/dist_train.sh ./configs/det/faster-rcnn_r50_fpn_8e_mot20-half.py 8 --work-dir ./work_dirs/
and it gave me an error "The module torch.distributed.launch is deprecated, use torchrun."
So i looked it up and  at pytorch website i found [this.](https://pytorch.org/docs/stable/elastic/run.html#launcher-api)
I need to modify the training script to get it done but i couln't do it. So i was wondering if you could tell me how to modify my train script.

**Comment by dyhBUPT** [comment]
What's the version of your pytorch?
And it's an error or a warning?

**Comment by mehmetcanmitil** [comment]
My pytorch version is 1.11.0.
it's a warning but still cant train. Also gives me this error: torch.distributed.elastic.multiprocessing.errors.ChildFailedError:

**Comment by dyhBUPT** [comment]
It seems that the "ChildFailedError" is not caused by "torch.distributed.launch", because it just a warning as in the [source code](https://github.com/pytorch/pytorch/blob/f94abd59f70f0327862e2bd4dc3e3ea28fed05f0/torch/distributed/launch.py#L179) of pytorch.
I can't give any solutions with your limited description.
Please use the issue template to describe your problem and show the full error information.

Or you can also try the pytorch<1.10, like 1.8. Because the "torchrun" is added in the pytorch 1.10.

Best wishes.

**Comment by dyhBUPT** [comment]
Glad to hear that you have solved the problem.
Smaller batch size would help with the memory error.

Best wishes.

**Comment by mehmetcanmitil** [comment]
Hi, hate to ask a lot of questions but i couldn't figure out how to change the batch size. 
I dont see anything about batch size in the training scripts.Can you help me find where it is?

**Comment by dyhBUPT** [comment]
Hi, you can set the batch size by the "samples_per_gpu".
For example, if you are training the detector and use the cfg "faster-rcnn_r50_fpn_8e_mot20-half.py", you can change the code from 
```python
data = dict(
    train=dict(
        ann_file=data_root + 'annotations/half-train_cocoformat.json',
        img_prefix=data_root + 'train'),
    val=dict(
        ann_file=data_root + 'annotations/half-val_cocoformat.json',
        img_prefix=data_root + 'train'),
    test=dict(
        ann_file=data_root + 'annotations/half-val_cocoformat.json',
        img_prefix=data_root + 'train'))
```
to
```python
data = dict(
    samples_per_gpu=1,
    train=dict(
        ann_file=data_root + 'annotations/half-train_cocoformat.json',
        img_prefix=data_root + 'train'),
    val=dict(
        ann_file=data_root + 'annotations/half-val_cocoformat.json',
        img_prefix=data_root + 'train'),
    test=dict(
        ann_file=data_root + 'annotations/half-val_cocoformat.json',
        img_prefix=data_root + 'train'))
```
That is, batch_size=samples_per_gpu * num_gpus.
You can also refer to the [cfg example of a tracker](https://github.com/open-mmlab/mmtracking/blob/master/docs/en/tutorials/config_mot.md).

I'll be glad if this helps. Please feel free to contact me if you have any problems.
