### ISSUE TITLE
Something errors when test STARK on lasot

### ISSUE THREAD

**Issue by kuiran** [open-mmlab/mmtracking#567]
The config stark_st1_r50_500e_lasot.py seems wrong,it still test on got10k, I download the model you provide and test on lasot with the config I write as follows:
_base_ = ['./stark_st1_r50_500e_lasot.py']

data_root = '/home/ubuntu/mnt/dataset/kuiran/'
data = dict(
    test=dict(type='LaSOTDataset',
              ann_file='tools/convert_datasets/lasot/testing_set.txt',
              img_prefix=data_root + 'LaSOT/LaSOTBenchmark',
              split='test',
              test_mode=True,
              only_eval_visible=True
    )
)

But I get just 
![image](https://user-images.githubusercontent.com/25083462/169965752-f9cc3010-6bc4-4250-b707-4947d29e6a48.png)
It is lower that the performance you report, So what's wrong happened?

I also want to know how to evaluate the performance on GOT10k?

**Comment by JingweiZhang12** [comment]
Thanks for your feedback. Can you fix the error about configs of lasot?
As for the precision of STARK-ST1 on LaSOT, please make sure you use the latest code because the `tools/convert_datasets/lasot/testing_set.txt` is a deprecated annotation file we have not supported in the newest version of code.  
We now provide a new tutorial about converting dataset in SOT, https://github.com/open-mmlab/mmtracking/blob/master/docs/en/dataset.md.

**Comment by JingweiZhang12** [comment]
@kuiran I have tested the model of `STARK-ST1` and `STARK-ST2` on `LaSOT` using our latest code. The performance varies around 0.1. All is fine.

**Comment by JingweiZhang12** [comment]
We fix the bug of configs: https://github.com/open-mmlab/mmtracking/pull/572
